### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'allennlp.data.tokenizers.word_splitter'

### ISSUE THREAD

**Issue by lanlanlan3** [ConvLab/ConvLab-3#100]
**Describe the bug**
ModuleNotFoundError: No module named 'allennlp.data.tokenizers.word_splitter'

system env: 
macbook pro m1, ventura 13.0.1
Anaconda3-2022.10-MacOSX-arm64

conda env: 
conda create -n convlab3 python=3.9
pip install -e .
pip install allennlp, overrides

**To Reproduce**
1. Go to tutorials/Getting_Started.ipynb 
2. Click on the first cell of "build an agent"

**Expected behavior**
no bug

**Actual behavior**
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/folders/4t/jbjy985148dd53fy6b34rtjw0000gn/T/ipykernel_47306/1050441968.py:3 in <module>     │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/var/folders/4t/jbjy985148dd53fy6b34rtjw0000gn/T/ipykernel_47306/1050441968.py'                 │
│                                                                                                  │
│ /Users/***/03nlp/chatbot/ConvLab-3/convlab/nlu/milu/multiwoz/__init__.p │
│ y:1 in <module>                                                                                  │
│                                                                                                  │
│ ❱ 1 from convlab.nlu.milu.multiwoz.nlu import MILU                                               │
│   2                                                                                              │
│                                                                                                  │
│ /Users/***/03nlp/chatbot/ConvLab-3/convlab/nlu/milu/multiwoz/nlu.py:12  │
│ in <module>                                                                                      │
│                                                                                                  │
│     9 import torch                                                                               │
│    10 from allennlp.common.checks import check_for_gpu                                           │
│    11 from allennlp.data import DatasetReader                                                    │
│ ❱  12 from allennlp.data.tokenizers.word_splitter import SpacyWordSplitter                       │
│    13 # from allennlp.data.tokenizers import spacy_tokenizer                                     │
│    14 from allennlp.models.archival import load_archive                                          │
│    15                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'allennlp.data.tokenizers.word_splitter'

**Additional context**

**Comment by zqwerty** [comment]
I think this is caused by allennlp version. MILU requires allennlp==0.9.0 which is incompatible with latest version. see https://github.com/ConvLab/ConvLab-3/tree/master/convlab/nlu/milu to setup python environment

**Comment by lanlanlan3** [comment]
fixed, thanks a lot
