### ISSUE TITLE
preprocess.py in jointBERT / unified_datasets [BUG] 

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#108]
I was trying to use JointBERT NLU for sgd dataset. I got the following error

![Screen Shot 1444-05-25 at 12 08 35 PM](https://user-images.githubusercontent.com/7421065/208389705-cadd913b-353d-4959-ad98-4a5d2cdb4f35.png)

**Comment by zqwerty** [comment]
You have to install convlab first (if you use colab, remember to restart the kernel)

**Comment by zqwerty** [comment]
BTW, a proper command is `python preprocess.py --dataset sgd --speaker all --context_window_size 3 --save_dir save_directory`

**Comment by AtheerAlgherairy** [comment]
> 

Thanks.. It's worked. 

But when I tried to train the model, I got this error:

%run train.py --config_path XXXX

![Screen Shot 1444-05-26 at 11 46 49 AM](https://user-images.githubusercontent.com/7421065/208623737-23f7f684-dbb7-49e3-a504-c3da4ad53482.png)

**Comment by AtheerAlgherairy** [comment]
It is worked. Thanks
