### ISSUE TITLE
JointBERT NLU training for sgd dataset (system) [BUG] 

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#109]
I did the preprocessing step and added the directory of the preprocessed data in the config file. When I tried to do the training, I got the following error:

%run train.py --config_path xxxx\sgd_sys_context3.json

![Screen Shot 1444-05-26 at 11 46 49 AM](https://user-images.githubusercontent.com/7421065/208631841-1061e525-1c60-4eb9-a848-46cb24b02454.png)

**Comment by zqwerty** [comment]
Could you check whether the data dir contains `unified_datasets`? As in line 35 of `train.py`, I import `recover_intent` according to the data dir (to be compatible with convlab-2 code)

**Comment by AtheerAlgherairy** [comment]
> 

![Screen Shot 1444-05-26 at 12 40 25 PM](https://user-images.githubusercontent.com/7421065/208634889-aa008600-66e5-41b5-89e8-8de8e751cd7e.png)

**Comment by zqwerty** [comment]
I mean the `data_dir` arg in config file

**Comment by AtheerAlgherairy** [comment]
> I mean the `data_dir` arg in config file
> https://github.com/ConvLab/ConvLab-3/blob/master/convlab/nlu/jointBERT/train.py#L35

in config file:
  "data_dir": "C:/Users/g201906730/Desktop/preprocessed_sgd/sgd/system/context_window_size_3",

**Comment by AtheerAlgherairy** [comment]
Should I put:
"data_dir":  "unified_datasets/data/sgd/system/context_window_size_3"
?

**Comment by zqwerty** [comment]
You can move/rename the data_dir as long as it contains `unified_datasets`. Or you can modify the `train.py` by adding `from convlab.nlu.jointBERT.unified_datasets.postprocess import is_slot_da, calculateF1`

**Comment by zqwerty** [comment]
> Should I put: "data_dir": "unified_datasets/data/sgd/system/context_window_size_3" ?

That's the behavior I expected
