### ISSUE TITLE
NLU Usage for JointBERT and sgd dataset [BUG] 

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#111]
I've already trained the model on sgd user (context=3). I am trying to use it now (i.e. nlu.predict) but I got the following error:
![Screen Shot 1444-05-28 at 12 58 13 PM](https://user-images.githubusercontent.com/7421065/209109415-02037913-82d3-4b95-859c-d8930b611d8c.png)

![Screen Shot 1444-05-28 at 12 58 44 PM](https://user-images.githubusercontent.com/7421065/209109450-71408d26-52fb-44df-a744-de3983b9f48e.png)

**Comment by zqwerty** [comment]
Did you install the convlab through pip? the `data`  dir is not included in pip installation. You can try git clone and install

**Comment by AtheerAlgherairy** [comment]
I use (git clone). 

![Screen Shot 1444-06-02 at 11 00 55 AM](https://user-images.githubusercontent.com/7421065/209521928-2aa17414-a9e3-4370-ab4b-0250685b4b88.png)

**Comment by zqwerty** [comment]
Have you met the problem before? In my machine the import `from data.unified_datasets.multiwoz21.preprocess import reverse_da, reverse_da_slot_name_map` raise no error.

you may re-install the convlab through `pip install -e .` If the problem still exists, try to replace the import with `reverse_da = relative_import_module_from_unified_datasets('multiwoz21', 'preprocess.py', 'reverse_da_slot_name_map')`

**Comment by AtheerAlgherairy** [comment]
Now it is working. I moved the data folder inside (convlab) folder and changed the import to :

from convlab.data.unified_datasets.multiwoz21.preprocess import reverse_da, reverse_da_slot_name_map

**Comment by AtheerAlgherairy** [comment]
![Screen Shot 1444-06-02 at 12 34 30 PM](https://user-images.githubusercontent.com/7421065/209532599-4cf7e03d-71d9-483f-be79-4b95d60e4cf2.png)

I used the model that I've trained and saved (following the steps under: nlu\jointBERT\unified_datasets).
It works and gives prediction, but is this warning message ok?

**Comment by zqwerty** [comment]
Yes it is ok. it is telling that the pre-trained bert's cls head is not used

**Comment by zqwerty** [comment]
> Now it is working. I moved the data folder inside (convlab) folder and changed the import to :
> 
> from convlab.data.unified_datasets.multiwoz21.preprocess import reverse_da, reverse_da_slot_name_map

it is a kind of work-around. I would recommend using `relative_import_module_from_unified_datasets`. I will update the repo with this
