### ISSUE TITLE
base_models/BERT 

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#121]
What is the difference between JointBERT and base_models/BERT for NLU task?

is there a "read me" file or tutorial for the later?

(https://github.com/ConvLab/ConvLab-3/tree/master/convlab/base_models/bert)

Many thanks

**Comment by zqwerty** [comment]
Base_model Bert is not ready

发自我的iPhone

在 2023年1月19日，18:25，Atheer Algherairy ***@***.***> 写道：

﻿

What is the difference between JointBERT and base_models/BERT for NLU task?

is there a "read me" file or tutorial for the later?

(https://github.com/ConvLab/ConvLab-3/tree/master/convlab/base_models/bert)

Many thanks
