### ISSUE TITLE
soloist.py import error[BUG] 

### ISSUE THREAD

**Issue by haziyevv** [ConvLab/ConvLab-3#127]
In convlab/e2e/soloist/multiwoz/soloist.py 

in 13th line SOLOIST is tried to be imported from soloist_net, but soloist_net.py does not exist.

from convlab.e2e.soloist.multiwoz.soloist_net import SOLOIST, cuda_

**Comment by zqwerty** [comment]
@pengbaolin it seems that the `SOLOIST` class is removed and the `soloist_net` is replaced by `train.py` (Commit [4d7d80](https://github.com/ConvLab/ConvLab-3/commit/4d7d80c5a00acf5de7f46d698f4ccc5d004c7ba2). Could you modify the interface of `SOLOISTAgent`?

**Comment by pengbaolin** [comment]
restored the file. auto merged to master. Thanks!
