### ISSUE TITLE
Example scripts for rule dst and policy raise AssertionError

### ISSUE THREAD

**Issue by YoheiHayamizu** [ConvLab/ConvLab-3#130]
I ran the example script in [RuleDST](https://github.com/ConvLab/ConvLab-3/tree/ae50d9d3619ff88d89b4de5e58b760781efe7d2a/convlab/dst/rule/multiwoz) and [RulePolicy](https://github.com/ConvLab/ConvLab-3/tree/ae50d9d3619ff88d89b4de5e58b760781efe7d2a/convlab/policy/rule/multiwoz) and got AssersionErrors. 
It's just because those scripts are outdated, and can I ignore them? Thanks!

**Comment by zqwerty** [comment]
Thanks! I've update the example script of RuleDST

For RulePolicy, could you provide the error message? I am not sure which example is broken.

**Comment by YoheiHayamizu** [comment]
Sorry, it was all in my head. RulePolicy works fine.
