### ISSUE TITLE
T5 for DST (evaluation results)

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#132]
I fine-tuned T5 for DST. I got the (predict metrics) after evaluation. Then, I used "merge_predict_res" and  "evaluate_unified_datasets", I got different results.. why?

![Screen Shot 1444-07-09 at 1 30 41 PM](https://user-images.githubusercontent.com/7421065/215736500-49c65241-8946-423a-9400-fad028d87d41.png)

evaluate_unified_datasets results:
![Screen Shot 1444-07-09 at 1 30 56 PM](https://user-images.githubusercontent.com/7421065/215737269-6992fb35-0976-49f4-a8d6-30ab5c761cc9.png)

**Comment by zqwerty** [comment]
The first result is calculated by `dst_metric.py` and the second one is by `dst/evaluate_unified_datasets.py`. The latter assumes the golden state contains all slot-value pairs of involved domains, and ignores the prediction out of this scope.

For example, if a model predicts `Hotel-Ticket-Free` which is not a valid domain-slot, the latter will ignore it while the former will regard it as an error prediction. In other words, the latter use the golden state as a filter to ignore invalid domain-slot predictions.

**Comment by AtheerAlgherairy** [comment]
Thank you for the clarification.

![Screen Shot 1444-07-10 at 10 25 40 AM](https://user-images.githubusercontent.com/7421065/215978215-0bc24179-8e3d-4685-8725-1fa5b83357cb.png)

Regarding the returned state by dst.update() method. The 'system_action': [], 'user_action': [] when/where they need to be filled?

**Comment by zqwerty** [comment]
If the DST model is used to build a system agent, the agent should pass the user_action (from NLU) and system_action (from Policy). You can look into the policy model (eg. DDPT) who needs this feature as input

**Comment by AtheerAlgherairy** [comment]
The prediction accuracy is the Joint goal accuracy (JGA), right ?

**Comment by zqwerty** [comment]
Yes
