### ISSUE TITLE
[BUG] Should use "-" instead of "_" to connect dialogue act.

### ISSUE THREAD

**Issue by trtd56** [ConvLab/ConvLab-3#133]
**Describe the bug**

When example code PPO.py is run, ValueError occurs.

```
File [MY CURRENT DIRECTORY]/ConvLab-3/convlab/util/multiwoz/lexicalize.py:37, in deflat_da(meta)
     35 dialog_act = {}
     36 for da in meta:
---> 37     d, i, s, v = da.split('_')
     38     k = '_'.join((d, i))
     39     if k not in dialog_act:

ValueError: not enough values to unpack (expected 4, got 1)
```

In [VectorBase class](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/policy/vector/vector_base.py), the dialogue act is joined and split by `_`, but [ontology](https://github.com/ConvLab/ConvLab-3/blob/master/data/multiwoz/ontology.json) is connected by `-`.

Use `-` to join and split. Or replace `-` with `_` of vec2act and act2vec in VectorBase class initialization.

**To Reproduce**

Run [examples/agent_examples/test_PPO.py](https://github.com/ConvLab/ConvLab-3/blob/master/examples/agent_examples/test_PPO.py).

The original code gets the PPO arguments wrong, so fix [line 22](https://github.com/ConvLab/ConvLab-3/blob/6109627bcd19a971d7d8f3fcc59f95d024c59496/examples/agent_examples/test_PPO.py#L22) that:
```diff
- sys_policy = PPO(False, seed=seed, use_action_mask=True, shrink=False)
+ sys_policy = PPO(False, seed=seed)
```

I use seed=0 and n_dialogues=10 but it does not matter.

**Expected behavior**
PPO.py runs without error.

**Actual behavior**
as stated above

**Additional context**
I have only tried PPO.py but this bug may affect some other code as the VectorBase class is used by many modules.

**Comment by ChrisGeishauser** [comment]
Hi! Thanks a lot for reporting this bug. I changed it from "-" to "_" because it created issues in the crosswoz dataset. But i will work on a general way the next days and let you know here once i fixed it :)

**Comment by ChrisGeishauser** [comment]
Hi @trtd56 , i pushed a new version that works without any splitting but uses tuples instead. Could you check whether the new code works for you? Thanks!

**Comment by trtd56** [comment]
Sorry for the late reply.
Just checked and it works fine!
Thank you!

**Comment by ChrisGeishauser** [comment]
Awesome, thanks for checking!
