### ISSUE TITLE
MultiWozEvaluator's add_sys_da doesn't use self.cur_domain

### ISSUE THREAD

**Issue by trtd56** [ConvLab/ConvLab-3#143]
This may be a boring question.
In the previous version (ConvLab-2), MultiWozEvaluator's add_sys_da used self.cur_domain to update self.booked. However, the current version (this ConvLab-3) does not.

[convlab2's multiwoz_eval.py L102-106](https://github.com/thu-coai/ConvLab-2/blob/e27290c0d82bf133077c8cf9fa7efdb3734e5b92/convlab2/evaluator/multiwoz_eval.py#L102)
```python
if da == 'booking-book-ref' and self.cur_domain in ['hotel', 'restaurant', 'train']:
    if not self.booked[self.cur_domain] and re.match(r'^\d{8}$', value) and \
            len(self.dbs[self.cur_domain]) > int(value):
        self.booked[self.cur_domain] = self.dbs[self.cur_domain][int(value)].copy()
        self.booked[self.cur_domain]['Ref'] = value
```

[the same process in convlab3; multiwoz_eval.py L190-104](https://github.com/ConvLab/ConvLab-3/blob/c490c21489cab244e1eeb7f1b859a1ea66c3f76e/convlab/evaluator/multiwoz_eval.py#L190)
```python
if not self.booked[domain] and re.match(r'^\d{8}$', value) and \
        len(self.dbs[domain]) > int(value):
    self.booked[domain] = self.dbs[domain][int(
        value)].copy()
    self.booked[domain]['Ref'] = value
```

Both update self.cur_domain like that: 
```python
# convlab2 L96,97 / convlab3 L177,178
if domain in belief_domains and domain != self.cur_domain:
    self.cur_domain = domain
```

But it is only used ConvLab-2.

I don't see any errors, so it may be fine as it is, but why?

**Comment by zqwerty** [comment]
This change is from this commit 027f3425635096d0bd57684e0392ac6b11db24b9
where we unified the data format for MultiWOZ 2.1, specifically, we change the booking act in here https://github.com/ConvLab/ConvLab-3/blob/c490c21489cab244e1eeb7f1b859a1ea66c3f76e/data/unified_datasets/multiwoz21/preprocess.py#L780

**Comment by trtd56** [comment]
Thank you reply.

I understand that the dialog act was modified to establish uniformity in the data format. However, why isn't self.cur_domain used to update self.booked?
```diff
- # convlab2
- self.booked[self.cur_domain] = self.dbs[self.cur_domain][int(value)].copy()
- self.booked[self.cur_domain]['Ref'] = value
+ convlab3
+ self.booked[domain] = self.dbs[domain][int(value)].copy()
+ self.booked[domain]['Ref'] = value
```
Does this indicate that domain and self.cur_domain will invariably be identical from convlab-3?

**Comment by zqwerty** [comment]
I think so.
https://github.com/ConvLab/ConvLab-3/blob/c490c21489cab244e1eeb7f1b859a1ea66c3f76e/convlab/evaluator/multiwoz_eval.py#L177-L178

**Comment by trtd56** [comment]
I see. I understand.
Thank you!
