### ISSUE TITLE
Replicating the performance of T5-small (context=3) NLU on MultiWOZ 2.1

### ISSUE THREAD

**Issue by kedudzic** [ConvLab/ConvLab-3#145]
Hello, I'm trying to understand how were those numbers achieved for the T5-small (context=3) NLU model on the MultiWOZ 2.1 dataset:
![Screenshot 2023-03-05 at 19-52-28 ConvLab_ConvLab-3](https://user-images.githubusercontent.com/80589373/222980159-3b46f45f-4767-499f-b441-9ecc7474d644.png)
I'd like to replicate this performance locally but I'm probably misunderstanding how it was calculated or just doing something wrong. There doesn't seem to be a training script in the [T5 NLU directory](https://github.com/ConvLab/ConvLab-3/tree/master/convlab/base_models/t5/nlu) for this model, so I made my own consulting the [HF model page](https://huggingface.co/ConvLab/t5-small-nlu-multiwoz21-context3):
```
n_gpus=1
task_name="nlu"
dataset_name=multiwoz21
speaker="user"
context_window_size=3
data_dir="data/${task_name}/${dataset_name}/${speaker}/context_${context_window_size}"
output_dir="output/${task_name}/${dataset_name}/${speaker}/context_${context_window_size}"
cache_dir="../cache"
logging_dir="${output_dir}/runs"
train_file="${data_dir}/train.json"
validation_file="${data_dir}/validation.json"
test_file="${data_dir}/test.json"
metric_name_or_path="nlu_metric.py"
metric_for_best_model="overall_f1"
source_column="context"
target_column="dialogue_acts_seq"
truncation_side="left"
max_source_length=512
max_target_length=512
model_name_or_path="t5-small"
per_device_train_batch_size=128
per_device_eval_batch_size=64
gradient_accumulation_steps=2
lr=1e-3
num_train_epochs=10

python ../create_data.py -t ${task_name} -d ${dataset_name} -s ${speaker} -c ${context_window_size}

python ../run_seq2seq.py \
    --task_name ${task_name} \
    --train_file ${train_file} \
    --validation_file ${validation_file} \
    --source_column ${source_column} \
    --target_column ${target_column} \
    --max_source_length ${max_source_length} \
    --max_target_length ${max_target_length} \
    --truncation_side ${truncation_side} \
    --model_name_or_path ${model_name_or_path} \
    --do_train \
    --do_eval \
    --save_strategy epoch \
    --evaluation_strategy epoch \
    --save_total_limit 1 \
    --prediction_loss_only \
    --cache_dir ${cache_dir} \
    --output_dir ${output_dir} \
    --logging_dir ${logging_dir} \
    --overwrite_output_dir \
    --preprocessing_num_workers 4 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --learning_rate ${lr} \
    --num_train_epochs ${num_train_epochs} \
    --optim adafactor \
    --gradient_checkpointing

python ../run_seq2seq.py \
    --task_name ${task_name} \
    --test_file ${test_file} \
    --source_column ${source_column} \
    --target_column ${target_column} \
    --max_source_length ${max_source_length} \
    --max_target_length ${max_target_length} \
    --truncation_side ${truncation_side} \
    --model_name_or_path ${output_dir} \
    --do_predict \
    --predict_with_generate \
    --metric_name_or_path ${metric_name_or_path} \
    --cache_dir ${cache_dir} \
    --output_dir ${output_dir} \
    --logging_dir ${logging_dir} \
    --overwrite_output_dir \
    --preprocessing_num_workers 4 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --learning_rate ${lr} \
    --num_train_epochs ${num_train_epochs} \
    --optim adafactor \
    --gradient_checkpointing

python merge_predict_res.py -d ${dataset_name} -s ${speaker} -c ${context_window_size} -p ${output_dir}/test_generated_predictions.json

python ../../../nlu/evaluate_unified_datasets.py -p ${output_dir}/predictions.json
```
But the performance I got with a model trained this way is subpar:
```
{'accuracy': 0.5291644058600109,
 'binary': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'non-categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'overall': {'f1': 0.649805447470817,
             'precision': 0.8097811027985592,
             'recall': 0.5426104715930189}} 
```
Next, I tried a second approach where I just downloaded the trained model from HF and did predictions with it, but the performance was the same:
```
{'accuracy': 0.5294357026587087,
 'binary': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'non-categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'overall': {'f1': 0.6505221061986226,
             'precision': 0.8097345132743363,
             'recall': 0.5436316375789083}}
```
Outputs are from `evaluate_unified_datasets.py`, which is run as part of the .sh script as can be seen above. Judging by what's written [here](https://github.com/ConvLab/ConvLab-3/tree/master/convlab/nlu), it's what was used to calculate the "correct" performance of the model. I must be missing something. Can you help me with this?

**Comment by zqwerty** [comment]
That's weird. Did you look into the `${output_dir}/test_generated_predictions.json` or `${output_dir}/predictions.json`? Are you using the newest version of this file?

**Comment by zqwerty** [comment]
[test_generated_predictions.zip](https://github.com/ConvLab/ConvLab-3/files/10893966/test_generated_predictions.zip)
Here is my `${output_dir}/test_generated_predictions.json`

**Comment by kedudzic** [comment]
Thanks, so it seems like it's something on my side. I'll look further into it and report back.

**Comment by kedudzic** [comment]
Ok, I know where's the problem. A few days ago I struggled with making predictions because of those lines in the [trainer.py](https://github.com/ConvLab/ConvLab-3/blob/c490c21489cab244e1eeb7f1b859a1ea66c3f76e/convlab/base_models/t5/trainer.py#L198) file:
```
"max_length": self._max_length if self._max_length is not None else self.model.config.max_length,
"num_beams": self._num_beams if self._num_beams is not None else self.model.config.num_beams,
```
Without any changes, they kept causing the following error when I tried to do predictions:
```
Traceback (most recent call last):
  File "../run_seq2seq.py", line 683, in <module>
    main()
  File "../run_seq2seq.py", line 637, in main
    predict_results = trainer.predict(predict_dataset, metric_key_prefix=file_prefix)
  File "/home/ked/anaconda3/envs/cl3_3/lib/python3.8/site-packages/transformers/trainer_seq2seq.py", line 135, in predict
    return super().predict(test_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/home/ked/anaconda3/envs/cl3_3/lib/python3.8/site-packages/transformers/trainer.py", line 2870, in predict
    output = eval_loop(
  File "/home/ked/anaconda3/envs/cl3_3/lib/python3.8/site-packages/transformers/trainer.py", line 2974, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/home/ked/cl3_3/ConvLab-3/convlab/base_models/t5/trainer.py", line 198, in prediction_step
    "max_length": self._max_length if self._max_length is not None else self.model.config.max_length,
AttributeError: 'ConvLabSeq2SeqTrainer' object has no attribute '_max_length'
```
I ended up changing them to get rid of that error, which let me successfully do predictions:
```
"max_length": self.model.config.max_length,
"num_beams": self.model.config.num_beams,
```
...and forgot I changed them. This causes the values for the parameters to be wrong (max_length=20, num_beans=1 I think) and gives me bad results. Just now I hardcoded them as:
```
"max_length": 100,
"num_beams": 1,
```
This gives me much better results:
```
{'accuracy': 0.8204015192620727,
 'binary': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'non-categorical': {'f1': 0.0, 'precision': 0.0, 'recall': 0.0},
 'overall': {'f1': 0.9035482258870564,
             'precision': 0.8847762256428507,
             'recall': 0.9231340512439659}}
```
So my question is: are those 2 lines in the` trainer.py `file correct? Or again is there a possibility that it's something on my end?

**Comment by zqwerty** [comment]
It is the problem of `transformers` version:
In 4.20.1 (my version): the `self._max_length` and `self._num_beams` are initialized in `Seq2SeqTrainer::evaluate` func
https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/trainer_seq2seq.py#L68
In 4.26.1 (newest version): these two variables are replaced by wrapping into `self._gen_kwargs`
https://github.com/huggingface/transformers/blob/ae54e3c3b18bac0832ad62ea9b896dfd52a09850/src/transformers/trainer_seq2seq.py#L71

**Comment by kedudzic** [comment]
Thank you very much! I can confirm it works as it should after switching to `transformers` 4.20.1. So the problem is solved. But I'm wondering, since I was doing all of that in a clean environment with just ConvLab-3 installed, the `transformers` version that was causing those errors was 4.24.0, installed through the [requirements.txt](https://github.com/ConvLab/ConvLab-3/blob/c490c21489cab244e1eeb7f1b859a1ea66c3f76e/requirements.txt#L114) file. Shouldn't it be lower? Right now, as in my case, it seems that you can't run the [T5 NLU scripts](https://github.com/ConvLab/ConvLab-3/tree/master/convlab/base_models/t5/nlu) without errors directly after installing ConvLab-3, since you have to manually downgrade `transformers` first. The wrapping in 4.24.0 is the same as in 4.26.1: https://github.com/huggingface/transformers/blob/94b3f544a1f5e04b78d87a2ae32a7ac252e22e31/src/transformers/trainer_seq2seq.py#L71

**Comment by zqwerty** [comment]
Thanks for your feedback! I'm sorry for the inconsistency. I will try to modify the code of `ConvLabSeq2SeqTrainer` and see if it can support a higher version. If not, I will update the env requirement.

**Comment by kedudzic** [comment]
Nice, thanks a lot for helping me!
