### ISSUE TITLE
Error with Seq2Seq2 training on multiple GPUs.

### ISSUE THREAD

**Issue by NoraAlt** [ConvLab/ConvLab-3#151]
I am encountering an error when trying to use the [Seq2Seq2 trainer](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/base_models/t5/run_seq2seq.py) to fine-tune T5 on multiple GPUs. The error message is as follows:

`../.conda/envs/stance/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
`

The warning message suggests that a gather operation is being performed along dimension 0 on a set of input tensors, but all of the input tensors are scalars. The error occurs during training and causes the training process to crash.

Note that when I set export `CUDA_VISIBLE_DEVICES=0` to ensure that the training runs on a single GPU, the training process completes successfully without the warning mentioned earlier.

I am using PyTorch `version 1.13.0`.

Can you please advise on how to resolve this error? Is there a specific configuration or setting that needs to be modified when using the Seq2Seq2 trainer to fine-tune T5 on multiple GPUs?

**Comment by zqwerty** [comment]
Could you share your script? I use the following command to enable multi-GPU 
```
python -m torch.distributed.launch \
    --nproc_per_node ${n_gpus} ../run_seq2seq.py \
```
https://github.com/ConvLab/ConvLab-3/blob/master/convlab/base_models/t5/rg/run_rg.sh

**Comment by NoraAlt** [comment]
The command worked perfectly, and I was able to complete the training without any further issues.

I really appreciate your prompt response and the time you took to help.
Have a great day!
