### ISSUE TITLE
Train MLE policy for sgd dataset

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#156]
I was trying to train MLE policy for sgd. I've added default_state in  convlab.util.sgd.state (similar to multiwoz21) but I got the following error. Would you please guid me in this:

![Screen Shot 1444-09-21 at 12 03 48 AM](https://user-images.githubusercontent.com/7421065/231289326-a3cc7008-e77a-4a43-900f-84d92696dab5.png)

**Comment by ChrisGeishauser** [comment]
Hi @AtheerAlgherairy! I pushed some changes and it worked for me now, can you try again? Please first delete the folder sgd_VectorBinary inside of policy/mle

**Comment by AtheerAlgherairy** [comment]
Thank you very much @ChrisGeishauser. It is worked and the training on SGD completed. 

I was trying to use the pre-trained model on SGD  but I got the following output (info for Multiwoz):

![Screen Shot 1444-10-10 at 1 00 40 PM](https://user-images.githubusercontent.com/7421065/235347273-8ae6292d-858e-4a54-a43a-bd246b0b982a.png)

**Comment by AtheerAlgherairy** [comment]
![Screen Shot 1444-10-11 at 11 11 09 AM](https://user-images.githubusercontent.com/7421065/235427300-06e02a69-726e-4a05-9671-ff192ca2e548.png)

**Comment by AtheerAlgherairy** [comment]
I was trying to pass a state to the MLE policy and use **predict** function, as follows:

![Screen Shot 1444-10-11 at 12 45 35 PM](https://user-images.githubusercontent.com/7421065/235436923-c981b02e-3f30-43b9-a265-8bb1bc72fd81.png)

The output above shows the generated state from DST.  I got the following error:


![Screen Shot 1444-10-11 at 12 48 54 PM](https://user-images.githubusercontent.com/7421065/235437122-3259bcc9-da89-4c59-86e1-631ccf12c09f.png)

**Comment by AtheerAlgherairy** [comment]
I changed dbquery_domain in vector_base.py to return an empty list since SGD doesn't have database, I got another error in the  lexicalize_da in lexicalize.py:

![Screen Shot 1444-10-11 at 12 58 00 PM](https://user-images.githubusercontent.com/7421065/235438323-151b0509-170c-4f92-a529-e8c45d195ef7.png)

**Comment by ChrisGeishauser** [comment]
Hi @AtheerAlgherairy! As you correctly observed, SGD has no database and hence no query is possible. Because of this, lexicalization would be only partially possible but you could never inform something from the database for instance. At the moment, the lexicalization function is only working with the multiwoz corpus and has not yet a generalization to other datasets. But we are very happy for any contribution to this!

**Comment by AtheerAlgherairy** [comment]
Thanks @ChrisGeishauser.

I extracted database for SGD from service_results element in the dialogues:
[https://github.com/AtheerAlgherairy/SGD_database](url)

**Comment by ChrisGeishauser** [comment]
Hi @AtheerAlgherairy. Did you use dataset_name = "multiwoz21"?

**Comment by AtheerAlgherairy** [comment]
After training **mle** on multiwoz, I got this folder:

![Screen Shot 1444-10-18 at 2 31 07 PM](https://user-images.githubusercontent.com/7421065/236813277-c5015255-a1d6-425c-aa90-0cd4300ecd55.png)

The resulted model should be here, right:
![Screen Shot 1444-10-18 at 2 33 08 PM](https://user-images.githubusercontent.com/7421065/236813412-d4008231-f1ec-4951-a00d-dbc64e1f9a56.png)

And here is the cofig file under configs folder:
![Screen Shot 1444-10-18 at 2 34 07 PM](https://user-images.githubusercontent.com/7421065/236813630-81561ab7-0d01-48fa-a7ea-b54b2fee6c06.png)

is there something missing?

**Comment by ChrisGeishauser** [comment]
Can you tell me how you initialised "sys_policy_mwoz"? And there is nothing missing for your data I think :)

**Comment by AtheerAlgherairy** [comment]
sys_policy_mwoz= MLEPolicy(model_file="C:/Users/g201906730/Desktop/ConvLab-3/convlab/policy/mle/experiments/experiment_2023-05-08-11-49-48/save/supervised.pol.mdl")

**Comment by AtheerAlgherairy** [comment]
When initializing mle policy with model file, the load_from_pretrained is called as follows:

`self.load_from_pretrained(archive_file, model_file, cfg['load'])`

The last argument cfg['load'] is for file_name which is here: save/best.  However, there is no such file name generated after mle training. 

the  load_from_pretrained function in mle.py uses this file name to load the model. it doesn't use the provided model_file.

**Comment by ChrisGeishauser** [comment]
Instead of loading the MLE policy, could you maybe just try to load the PPO policy? It uses the same architecture, so there is no difference when doing a prediction. 

`
from convlab.policy.ppo import PPO
policy_sys = PPO(dataset_name="multiwoz21", load_path="YOUR_MLE_EXPERIMENT_FOLDER/save/supervised")
`

The experiment folder is the one you mentioned above that also has the timestamp in it. You can also set load_path="from_pretrained" to automatically download a multiwoz model.

If you want to experiment with SGD, I would recommend you to take the DDPT policy instead:

`
from convlab.policy.vtrace_DPT import VTRACE
policy = VTRACE(dataset_name="sgd", load_path="from_pretrained")
`

**Comment by AtheerAlgherairy** [comment]
The dataset argument is not there.

![Screen Shot 1444-10-21 at 10 21 33 AM](https://github.com/ConvLab/ConvLab-3/assets/7421065/52f420c6-294f-4afb-8877-99c35091a272)

**Comment by ChrisGeishauser** [comment]
Can you pull the newest version and try again? It works for me.

**Comment by AtheerAlgherairy** [comment]
@ChrisGeishauser  Thank you..

**Comment by AtheerAlgherairy** [comment]
The SYS RESPONSE shouldn't be like this. right?

![Screen Shot 1444-11-02 at 12 38 57 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/34b8c606-201e-418b-b421-0a44d551dc62)

**Comment by AtheerAlgherairy** [comment]
Thanks @ChrisGeishauser .. I will try again.. 

 Is there Agenda Based User Simulator for SGD dataset?

**Comment by ChrisGeishauser** [comment]
Hi @AtheerAlgherairy! No, there is only an ABUS for MultiWOZ at the moment.
