### ISSUE TITLE
[Question/Issue] Should SOLOISTAgent condition generation on DB state?

### ISSUE THREAD

**Issue by kingb12** [ConvLab/ConvLab-3#159]
Hi all! Thanks for building this all out, its a very useful framework for interacting with dialogue systems. I was looking at `SOLOISTAgent`, and if I understand correctly, it does not actually condition on the DB result provided by a belief state, but instead:

1. predicts a belief state and delexicalized response at the same time
2. uses the belief state to fetch DB entries with a reader/rule-based matcher
3. lexicalizes items in the response with values from any DB entries found

If I understand right, the paper seems to imply that at response generation time, the number of DB entries found is known, and included in the input sequence:

![Screenshot 2023-04-26 at 4 40 02 PM](https://user-images.githubusercontent.com/12914639/234725114-0329ef6c-ee1a-4604-bc0a-1ac6837f190d.png)

Should there not be two generation steps, first generating a belief state, then a response based on state + retrieved DB entries? I thought this might be a bug but noticed a similar issue in the SOLOIST repo: https://github.com/pengbaolin/soloist/issues/2

Similarly, could one use the existing `SOLOISTAgent` approach to reproduce their MultiWOZ results, assuming you had the right pre-trained weights?

**Comment by zqwerty** [comment]
I have a look at `SOLOISTAgent` and it seems that SOLOIST generate belief state and response in one pass and then use db result to lexicalize response:

https://github.com/ConvLab/ConvLab-3/blob/04197837c424eb314bf47839a1a26f8a0048ff55/convlab/e2e/soloist/multiwoz/soloist.py#L135-L143

@pengbaolin Is this implementation different from the paper?

**Comment by zqwerty** [comment]
> Similarly, could one use the existing SOLOISTAgent approach to reproduce their MultiWOZ results, assuming you had the right pre-trained weights?

For this question, in ConvLab-3 we use a more general delexicalization method instead of the one tailored to MultiWOZ (which is used by end2end models in multiwoz but does not support other datasets). Beside, SOLOIST in ConvLab-3 use T5 as the backbone. So you may not get the same result as the paper.

**Comment by kingb12** [comment]
Ah that makes sense, thank you for the clarification!
