### ISSUE TITLE
[Maintenance] pip install convlab fails due to version conflict in Colab

### ISSUE THREAD

**Issue by kirilzilla** [ConvLab/ConvLab-3#161]
**Describe the feature**
Currently it is not possible to use the Tutorial Colab due to version conficts in convlab.

https://colab.research.google.com/github/ConvLab/ConvLab-3/blob/master/tutorials/Getting_Started.ipynb#scrollTo=qPqTs6EP0wxO

`! pip install convlab` ends in following error.
**ERROR: Cannot install convlab==3.0.0 and convlab==3.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    convlab 3.0.1 depends on deepspeech
    convlab 3.0.0 depends on deepspeech**

**Expected behavior**
pip install work successfully

**Additional context**
Add any other context about the feature here.

**Comment by zqwerty** [comment]
Thanks! It seems recently the `deepspeech` package is no longer usable. I will update the package requirements

**Comment by zqwerty** [comment]
update requirements.txt and release convlab==3.0.2a
