### ISSUE TITLE
[Questions] Training PPO policy 

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#164]
Hi,

I really appreciate the time and efforts you put in this project. I you don't mind, I have a question regarding training PPO policy:

**When I start training I got the following text files "unknown slots" and "Fuzzy recognition" (below). Does this mean there is something wrong ?**

![Screen Shot 1444-12-02 at 11 47 04 AM](https://github.com/ConvLab/ConvLab-3/assets/7421065/d9f82abf-7de0-4456-b8be-7d9f974d9bec)
![Screen Shot 1444-12-02 at 11 45 12 AM](https://github.com/ConvLab/ConvLab-3/assets/7421065/c23188ee-ad4c-4331-91f0-7d7e2cb70429)

Thank you for help and support..

**Comment by AtheerAlgherairy** [comment]
@ChrisGeishauser  the superhero of policy issues! 😁🙏 I kindly ask for your valuable support here..

**Comment by AtheerAlgherairy** [comment]
I am using GPU so the Visible device: cuda not CPU.  The training never finishes execution :)  
When I print queue.empty() or queue.qsize() it shows that the queue is empty.

**Comment by hsien1993** [comment]
In dst, the function `normalize_value` in `convlab/dst/rule/multiwoz/dst_util.py` may be called to normalize the value from NLU to the ontology. If the value cannot be normalized, then it will be recorded in the log.
