### ISSUE TITLE
[BUG] Evaluate PPO (using --goals_from_data )

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#165]
When I evaluate PPO policy using and add the argument --goals_from_data, I got the following error:

**This error when using GenTUS for evaluation:**

![Screen Shot 1444-12-30 at 1 03 59 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/256c671f-a655-4b98-9c90-24bd54e6954d)

![Screen Shot 1444-12-30 at 1 04 34 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/24b8a0ed-1a61-4929-ba97-5f55d83bbf1e)

**This error when using ABUS for evaluation:**

![Screen Shot 1444-12-30 at 1 12 27 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/a82d5bdf-51af-463c-8f5c-3faf4c0317fb)

**Comment by hsien1993** [comment]
Hi @AtheerAlgherairy 
This argument `--goals_from_data` is designed from GenTUS, so currently ABUS is not able to handle it. 
I updated the code, now I think you can use GenTUS with goals from the dataset.
