### ISSUE TITLE
[BUG] Evaluation of Rule based policy (RuleBasedMultiwozBot)

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#176]
The class RuleBasedMultiwozBot(Policy) uses the old format of state (i.e. the one with 'semi' key). 

![Screen Shot 1445-04-02 at 3 35 05 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/6cad12c4-9fa2-473a-bd22-daf5a8301d78)

**Comment by zqwerty** [comment]
Yes, the RuleBasedMultiwozBot is complicated and tailored to MultiWOZ dataset, so we will not support this in ConvLab-3.
