### ISSUE TITLE
How to evaluate RuleDST for Multiwoz2.1?

### ISSUE THREAD

**Issue by JamesCao2048** [ConvLab/ConvLab-3#192]
Hi, I have ran [evaluate.py](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/dst/rule/multiwoz/evaluate.py) to evaluate RuleDST for Multiwoz2.1 with unified data format.  There are two files generated,` predictions_BERTNLU-RuleDST.json` and `predictions_RuleDST.json` with golden user act. After that, I ran [evaluate_unified_datasets.py](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/dst/evaluate_unified_datasets.py) to  evaluate the two results, and get `{'accuracy': 0.3125339120998372,
'slot_f1': 0.8077468839884947,
'slot_precision': 0.8683689736682975,
'slot_recall': 0.7550366847501374}`, and  `{'accuracy': 0.38849701573521433, 'slot_f1': 0.8555441063299725, 'slot_precision': 0.9417643004824259, 'slot_recall': 0.7837870133594628}` respectively.

My questions are:
1. Why is the evaluation accuracy  of  `predictions_RuleDST.json` with golden user act not nearly   100%?
2. I found two possible reasons, but I do not know whether they are expected:
- System acts have not been taken into consideration. I have found that only user acts have been used to update the dialogue state in  [evaluate.py](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/dst/rule/multiwoz/evaluate.py) , and [DST](https://github.com/ConvLab/ConvLab-3/blob/master/convlab/dst/dst.py) also seems to only accept user acts . However, there are cases like the system would recommend some options with contraints, and then affect the dialogue state.  For example, in Multiwoz2.1 test data 'PMUL2437.json', the system recommend a restaurant and then user accept the recommendation.
- Data noise.  Somethimes the user may ask for a wrong task at first (such as want to book a restaurant with a name for attraction), and then correct it in later conversation.
3. Do other DST (like SetSumbt and Trippy) suffer from these two problems? These DST models generate dialogue state direcly from dialogue history, thus I think they would consider past system acts but I have not verified for this.

Thanks  a lot!
Looking forward to your reply,
James Cao

**Comment by zqwerty** [comment]
Yes, I think your reasons are correct. The design of RuleDST is to provide a simple rule baseline that only takes `inform` and `request` intent of user acts into accounts. However, accumulated user acts are not always consistent with dialog state and there are noise in dialog act annotations. Other DST models that are optimized to directly predict dialog state from the dialog context will implicitly/explicitly (depends on model) consider both user acts and system acts, so will not suffer from the two problems you mentioned

**Comment by JamesCao2048** [comment]
Thanks a lot!
