### ISSUE TITLE
[Question] TUS - Role of `num_token` for input feature and prediction

### ISSUE THREAD

**Issue by NoB0** [ConvLab/ConvLab-3#199]
Hello, thanks a lot for your work!

This is a question related to the implementation of the transformer-based user simulator. I see that there is a variable `num_token` used a in several places of the implementation, could please precise what does it correspond to?

Based on my understanding of the code, it is used to define the maximum length of the input feature vector (cf. function `pad_feature` in `convlab/policy/tus/multiwoz/user_manager.py) and it also serves to slice the output tensor of the transformer (cf. loss computation in `convlab/policy/tus/multiwoz/transformer.py`). According to the default configuration it is set to 65, how was this number chosen? (I can find a clear correlation between the description on the paper and the code)  

I guess @hsien1993 should be able to answer this question.

**Comment by NoB0** [comment]
Thanks for your answer @hsien1993 

Just to make sure I completely understand: `num_token` would be the maximum length of $V^t$ in the paper?
And the histories you mentioned corresponds to the number of turns $t$ considered to build $V_{input}$?

In the default case, you have `num_token=65` and `histories=5`, so the maximum length of $V_{input}$ would be 65*5 excluding the tokens [CLS] and [SEP], is that correct?

**Comment by hsien1993** [comment]
Hi @NoB0 

> `num_token` would be the maximum length of $V^t$ in the paper?

That is correct!

> the histories you mentioned correspond to the number of turns $t$ considered to build $V_{input}$?

That is also correct!

but the default history size is `3` not `5`. 
ref:    https://github.com/ConvLab/ConvLab-3/blob/60f4e5641f93e99b8d61b49cf5fd6dc818a83c4c/convlab/policy/tus/unify/exp/all.json#L23
https://github.com/ConvLab/ConvLab-3/blob/60f4e5641f93e99b8d61b49cf5fd6dc818a83c4c/convlab/policy/tus/unify/usermanager.py#L178

**Comment by NoB0** [comment]
Great, thank you for the clarification.
